eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: MyRibbonConsumer

hystrix:
  dashboard:
    proxyStreamAllowList: "localhost"

#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
